name: Modia
favicon: null
layout_spectrum: 0.721789448754862
typography_spectrum: 0.3316352458205074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.15885972464457154
  lightness: 0.9276107449550182
  saturation: 0.02510218764655292
  rhythmicContrast: 0.9238796348217875
purpose: []
